---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: infrastructure
spec:
  interval: 60m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 25.10.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 10m
  values:
    prometheus-node-exporter:
      enabled: false
    prometheus-pushgateway:
      enabled: false
    alertmanager:
      enabled: false
    kube-state-metrics:
      containerSecurityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      metricLabelsAllowlist:
        - pods=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
        - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
    configmapReload:
      prometheus:
        containerSecurityContext:
          allowPrivilegeEscalation: false
    server:
      strategy:
        type: Recreate
      
      retention: "14d"
      global:
        scrape_interval: 15s
        
      
    extraScrapeConfigs: |-
